# Generated by Django 5.1.1 on 2024-09-22 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.IntegerField(verbose_name='Выбранный ответ')),
                ('correct_answer', models.IntegerField(verbose_name='Верный ответ')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_passage', models.TimeField(verbose_name='Время выполнения')),
                ('test_scores', models.IntegerField(verbose_name='Баллы за ответы')),
                ('bonus_scores', models.IntegerField(verbose_name='Бонусные баллы')),
                ('total_scores', models.IntegerField(verbose_name='Итоговые баллы')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField(verbose_name='Название группы')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(verbose_name='Название роли')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_body', models.JSONField(verbose_name='Тело теста')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TopicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_type_name', models.TextField(verbose_name='Название темы')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedTestAnsweredTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_system.answeredtask')),
                ('finished_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_system.finishedtest')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scores', models.IntegerField(verbose_name='Общее количество баллов')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests_system.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='finishedtest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_system.profile'),
        ),
        migrations.AddField(
            model_name='answeredtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_system.task'),
        ),
        migrations.AddField(
            model_name='finishedtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_system.test'),
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_system.task')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_system.test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='topic_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_system.topictype'),
        ),
        migrations.AddField(
            model_name='task',
            name='topic_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_system.topictype'),
        ),
    ]
