# Generated by Django 5.1.1 on 2024-09-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0002_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finishedtest',
            old_name='user',
            new_name='profile',
        ),
    ]
