# Generated by Django 5.1.1 on 2024-10-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0003_rename_user_finishedtest_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_name',
            field=models.TextField(default=5, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
