# Generated by Django 5.1.1 on 2024-10-06 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0004_profile_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.TextField(verbose_name='Название')),
                ('image_path', models.TextField(verbose_name='Путь к файлу')),
                ('topic_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_system.topictype')),
            ],
        ),
    ]
