# Generated by Django 5.1.1 on 2024-10-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_path',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
