# Generated by Django 5.1.1 on 2024-10-08 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0006_remove_image_image_path_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='topic_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests_system.image'),
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_system.image')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_system.task')),
            ],
        ),
    ]
