# Generated by Django 5.1.1 on 2024-10-08 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0007_remove_image_topic_type_profile_profile_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh', models.TextField(verbose_name='Refresh')),
                ('date_create', models.DateTimeField(verbose_name='Дата генерации')),
                ('is_valid', models.BooleanField(verbose_name='Валиден')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_system.profile')),
            ],
        ),
    ]
