# Generated by Django 5.1.1 on 2024-10-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0009_remove_finishedtest_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_name',
        ),
    ]
