# Generated by Django 5.1.1 on 2024-11-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0013_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_scores',
            field=models.IntegerField(null=True, verbose_name='Общее количество баллов'),
        ),
    ]
