# Generated by Django 5.1.1 on 2024-11-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0014_alter_profile_total_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests_system.group'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests_system.image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_scores',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общее количество баллов'),
        ),
    ]
