# Generated by Django 5.1.1 on 2024-12-01 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0016_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
