# Generated by Django 5.1.1 on 2024-12-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0017_remove_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
