# Generated by Django 5.1.1 on 2024-12-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0018_delete_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_statement',
            field=models.TextField(default=1, verbose_name='Условие задания'),
            preserve_default=False,
        ),
    ]
