# Generated by Django 5.1.1 on 2024-12-01 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0019_task_task_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAnswersType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField(verbose_name='Тип ответов')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.TextField(default=1, verbose_name='Название теста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='answers_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tests_system.taskanswerstype'),
            preserve_default=False,
        ),
    ]
