# Generated by Django 5.1.1 on 2024-12-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0020_taskanswerstype_test_name_task_answers_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeredtask',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='task',
            name='correct_answer',
            field=models.IntegerField(default=1, verbose_name='Верный ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskanswerstype',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание типа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topictype',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание роли'),
            preserve_default=False,
        ),
    ]
