# Generated by Django 5.1.1 on 2024-12-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0021_remove_answeredtask_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание роли'),
            preserve_default=False,
        ),
    ]
