# Generated by Django 5.1.1 on 2024-12-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0022_role_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
    ]
