# Generated by Django 5.1.1 on 2024-12-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0024_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topictype',
            name='description',
        ),
    ]
