# Generated by Django 5.1.1 on 2024-12-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0025_remove_topictype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests_system.image'),
        ),
    ]
