# Generated by Django 5.1.1 on 2024-12-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_system', '0027_test_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskImage',
        ),
    ]
